import { RuleTester } from 'eslint'
import rule from './no-agent-comments.mjs'

const ruleTester = new RuleTester({
  languageOptions: {
    ecmaVersion: 2022,
    sourceType: 'module',
  },
})

ruleTester.run('no-agent-comments', rule, {
  valid: [
    '// Keep this order because the browser consumes the stream incrementally.\nconst value = 1',
    '/** Public contract: null means that no provider is available. */\nconst value = 1',
    '// eslint-disable-next-line complexity -- exhaustive switch over a closed union\nconst value = 1',
    '// UpdatedAt is a persisted timestamp.\nconst value = 1',
  ],
  invalid: [
    {
      code: '// Updated the parser during cleanup.\nconst value = 1',
      errors: [{ messageId: 'changeNarration' }],
    },
    {
      code: '/** Generated by Codex. */\nconst value = 1',
      errors: [{ messageId: 'aiAttribution' }],
    },
    {
      code: '// See EPIC-11.2 prompt 05.\nconst value = 1',
      errors: [{ messageId: 'epicReference' }],
    },
    {
      code: '// eslint-disable-next-line complexity\nconst value = 1',
      errors: [{ messageId: 'unexplainedDisable' }],
    },
  ],
})
