/**
 * @gami/shared — shared types and utilities
 *
 * This package is the single source of truth for types
 * used across apps in this monorepo.
 */

export type { ApiResponse, ApiError, ResponseMeta, ErrorCode } from './api-response.js'
export { ok, fail } from './api-response.js'
export {
  MODEL_PROVIDER_NAMES,
  MODEL_SELECTION_PROVIDER_NAMES,
  getModelPresetOptions,
  isAllowedModelForProvider,
  isModelProviderName,
  isModelSelectionProviderName,
} from './model-catalog.js'
export {
  AVATAR_COMPUTED_TRAIT_KEYS,
  AVATAR_COMPUTED_TRAIT_LABELS,
  coerceAvatarComputedTraits,
  createEmptyAvatarComputedTraits,
} from './avatar-computed-traits.js'
export type {
  ModelPresetOption,
  ModelProfile,
  ModelProviderName,
  ModelSelectionOverride,
  ModelSelectionProviderName,
  ScenarioModelSelection,
} from './model-catalog.js'
export type {
  AvatarStatus,
  AvatarLlmOverride,
  AvatarComputedTraits,
  AvatarSummary,
  CreateAvatarRequest,
  UpdateAvatarRequest,
  LifecycleStatus,
  ScenarioStatus,
  ScenarioSummary,
  ScenarioAvatarAvailability,
  SessionSummary,
  ConversationSummary,
} from './entity-types.js'
export type {
  ConversationEndReason,
  ConversationStartedBy,
  SessionMemorySummary,
  SessionMemoryLayers,
  SessionTransitionRecord,
  AvatarTransitionRecord,
  LifecycleSummary,
  EndConversationResponse,
} from './lifecycle-types.js'
export type {
  MessageMetadata,
  Message,
  AvatarMessageMetadata,
  SendMessageResponse,
  GetHistoryResponse,
  AvailableAvatarSummary,
  GetAvailableAvatarsResponse,
  SwitchAvatarResponse,
} from './conversation-contract-types.js'
export type {
  MessageStreamEventBase,
  MessageStreamStartedEvent,
  MessageStreamDeltaEvent,
  MessageStreamCompletedEvent,
  MessageStreamInterruptedEvent,
  MessageStreamErrorEvent,
  MessageStreamEvent,
} from './conversation-stream-contract-types.js'
export {
  isMessageStreamEvent,
  parseMessageStreamEvent,
} from './conversation-stream-contract-types.js'
export { parseSseDataFrame, processSseFrames } from './sse.js'
export type { RuntimeEvent, RuntimeState, GetRuntimeStateResponse } from './runtime-types.js'
export type {
  SharedMemoryFactRecord,
  SharedShortTermMemoryExchange,
  SharedShortTermMemorySnapshot,
  SharedWorkingMemoryCurrent,
  SharedWorkingMemorySessionSummary,
  SharedWorkingMemoryAvatarSummary,
  SharedLongTermMemoryFact,
  SharedLongTermAvatarMemory,
} from './memory-contract-types.js'
export type {
  KnowledgeType,
  KnowledgeSourceFormat,
  KnowledgeSourceStatus,
  IngestionJobStatus,
  KnowledgeVisibilityPolicy,
  KnowledgeSourceDto,
  KnowledgeChunkDto,
  IngestionJobDto,
  RetrievedKnowledgeItemDto,
  SharedContextScenarioSnapshot,
  SharedAvatarContextKnowledgeInjection,
  SharedTypedKnowledgeSections,
  SharedGmContextKnowledgeInjection,
  RecordedKnowledgeReferenceDto,
  RecordedTypedKnowledgeSections,
  RecordedAvatarContextKnowledgeInjection,
  RecordedGmContextKnowledgeInjection,
  CreateKnowledgeSourceRequest,
  CreateKnowledgeSourceResponse,
  ListKnowledgeSourcesQuery,
  ListKnowledgeSourcesResponse,
  UpdateKnowledgeSourceRequest,
  UpdateKnowledgeSourceResponse,
  DeleteKnowledgeSourceResponse,
  UploadKnowledgeSourceRequest,
  UploadKnowledgeSourceResponse,
  TriggerIngestionRequest,
  TriggerIngestionResponse,
  GetIngestionJobResponse,
  ListIngestionJobsResponse,
  ListKnowledgeChunksResponse,
  QueryKnowledgeRetrievalRequest,
  TypedKnowledgeRetrievalDto,
  QueryKnowledgeRetrievalResponse,
} from './knowledge-contract-types.js'
export type {
  UserPersona,
  UserSummary,
  UserPersonaResponse,
  UpsertUserPersonaResponse,
  GmStateSummary,
  AdminSessionInspectResponse,
  GmUnlockEvaluation,
  ConsumedGmRetrievalPlan,
  GmSessionEventPayload,
  MemoryRefreshEventPayload,
  TurnCompletedEventPayload,
  SessionEventRecord,
  AdminSessionEventsResponse,
  AdminSessionMemoryResponse,
  AdminSessionMemoryLayersResponse,
  TurnMetrics,
  TurnMetricsSummary,
  AdminSessionTurnMetricsResponse,
  RuntimeInspectorSnapshotResponse,
  ResetSessionAdminActionRequest,
  ResetSessionAdminActionResponse,
  EndConversationAdminActionRequest,
  SessionContextScenarioSnapshot,
  SessionContextAvatarWorkingMemory,
  SessionContextRecentMessage,
  SessionContextAvailableAvatar,
  SessionContextGmMemory,
  SessionContextAvatarSnapshot,
  SessionContextGmSnapshot,
  RecordedAvatarContextSnapshot,
  RecordedGmContextSnapshot,
  RecordedKnowledgeReference,
  SessionContextTrace,
  AdminSessionContextResponse,
  AdminReplayGmResponse,
  AdminRefreshMemoryResponse,
  AdminClearMemoryResponse,
  ModelConfigResponse,
  UpdateModelConfigRequest,
} from './runtime-inspector-types.js'
export type {
  ListScenariosResponse,
  CreateScenarioRequest,
  CreateScenarioResponse,
  UpdateScenarioRequest,
  UpdateScenarioResponse,
  GetScenarioResponse,
  DeleteScenarioResponse,
  ListScenarioAvatarsResponse,
  CreateAvatarResponse,
  UpdateAvatarResponse,
  DeleteAvatarResponse,
  AvatarTraitPreparationFailureReason,
  AvatarTraitPreparationResult,
  PrepareAvatarTraitsResponse,
  StartSessionRequest,
  StartSessionResponse,
  GetSessionResponse,
  ListSessionsQuery,
  ListSessionsResponse,
  ResetSessionResponse,
  StartConversationRequest,
  StartConversationResponse,
  ListSessionConversationsResponse,
  EndConversationRequest,
  ConversationHistoryApiResponse,
  GetAvailableAvatarsApiResponse,
  SwitchAvatarApiResponse,
  SendMessageRequest,
  SendMessageApiResponse,
  GetUserPersonaResponse,
  UpsertUserPersonaRequest,
  UpsertUserPersonaApiResponse,
  EndConversationApiResponse,
  LocalWebIdentity,
} from './web-contract-types.js'
