// DB adapters — infrastructure layer
// In-memory stubs are used in unit tests (injected via ServerAdapters).
// Postgres repositories are wired in production via apps/core/src/index.ts.
export { InMemoryAvatarRepository } from './in-memory-avatar.repository.js'
export { InMemoryGmStateRepository } from './in-memory-gm-state.repository.js'
export { InMemoryEventLogRepository } from './in-memory-event-log.repository.js'
export { InMemorySessionRepository } from './in-memory-session.repository.js'
export { InMemoryUserRepository } from './in-memory-user.repository.js'
export { InMemoryUserMemoryFactRepository } from './in-memory-user-memory-fact.repository.js'
export { InMemorySessionMemoryRepository } from './in-memory-session-memory.repository.js'
export { InMemoryAvatarSessionMemoryRepository } from './in-memory-avatar-session-memory.repository.js'
export { InMemoryConversationWorkingMemoryRepository } from './in-memory-conversation-working-memory.repository.js'
export { InMemoryMessageRepository } from './in-memory-message.repository.js'
export { InMemoryScenarioRepository } from './in-memory-scenario.repository.js'
export { PostgresScenarioRepository } from './repositories/postgres-scenario.repository.js'
export { PostgresAvatarRepository } from './repositories/postgres-avatar.repository.js'
export { PostgresGmStateRepository } from './repositories/postgres-gm-state.repository.js'
export { PostgresSessionRepository } from './repositories/postgres-session.repository.js'
export { PostgresConversationRepository } from './repositories/postgres-conversation.repository.js'
export { PostgresMessageRepository } from './repositories/postgres-message.repository.js'
export { PostgresEventLogRepository } from './repositories/postgres-event-log.repository.js'
export { PostgresUserRepository } from './repositories/postgres-user.repository.js'
export { PostgresUserMemoryFactRepository } from './repositories/postgres-user-memory-fact.repository.js'
export { PostgresSessionMemoryRepository } from './repositories/postgres-session-memory.repository.js'
export { PostgresAvatarSessionMemoryRepository } from './repositories/postgres-avatar-session-memory.repository.js'
export { PostgresConversationWorkingMemoryRepository } from './repositories/postgres-conversation-working-memory.repository.js'
export { InMemoryConversationRepository } from './in-memory-conversation.repository.js'
export { getDbClient, closeDbClient } from './client.js'
